#
# Copyright (c) 2015 Sam4Mobile
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
# Customize Kitchen with some monkey patching:
# - Suites scheduler
#   <% load "#{File.dirname(__FILE__)}/test/kitchen_command.rb" %>

driver:
  name: docker_cli

transport:
  name: docker_cli

provisioner:
  name: chef_zero

platforms:
  - name: centos-7
    driver_config:
      image: sbernard/centos-systemd-kitchen
      platform: centos
      # The two following lines are needed by systemd
      volume: /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /usr/sbin/init

suites:
  # Use dnsdock to provide a container name resolution
  - name: dnsdock
    includes: centos-7
    driver:
      hostname: dnsdock-zookeeper
      container_name: dnsdock-zookeeper
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - /var/run/docker.sock:/opt/run/docker.sock:ro
      run_command:
        - > # Everything needed to make dnsdock work in kitchen
          yum install -y go tar git &&
          mkdir -p /opt/go &&
          export GOPATH=/opt/go && export PATH=$PATH:/opt/go/bin &&
          go get -v github.com/tools/godep &&
          mkdir -p /opt/go/src/github.com/tonistiigi &&
          cd /opt/go/src/github.com/tonistiigi &&
          curl https://codeload.github.com/tonistiigi/dnsdock/tar.gz/v1.5.0 |
          tar xz && cd dnsdock-1.5.0 &&
          godep restore && go build &&
          mv dnsdock-1.5.0 /opt/go/bin/dnsdock &&
          echo -e '[Unit]\nDescription=dnsdock\n
          [Service]\nExecStart=/opt/go/bin/dnsdock
          -docker unix:///opt/run/docker.sock -domain=kitchen\n
          [Install]\nWantedBy=multi-user.target'
          > /usr/lib/systemd/system/dnsdock.service &&
          systemctl enable dnsdock

# Set var ip_of to use it in dns settings
<% ip_of = "docker inspect --format '{{.NetworkSettings.IPAddress}}'" %>
# Generate different types of nodes
<% { 'zookeeper' => 3 }.each do |name,n| %>
  <% ("01".."#{n}").each do |i| %>
  - name: <%= name %>-<%= i %>
    driver:
      hostname: <%= name %>-kitchen-<%= i %>.kitchen
      container_name: <%= name %>-kitchen-<%= i %>
      dns: $(<%= ip_of %> dnsdock-zookeeper)
    run_list:
      - role[<%= name %>-kitchen]
  <% end %>
<% end %>
