name 'zookeeper-cluster'
maintainer 'S4M'
maintainer_email 'samuel.bernard@s4m.io'
license 'all_rights'
description 'Installs/Configures a zookeeper-cluster'
long_description 'Installs/Configures a zookeeper-cluster'
version '1.0.0'

depends 'java'
depends 'ark'
