name 'zookeeper-cluster'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures zookeeper-cluster'
long_description 'Installs/Configures zookeeper-cluster'
version '0.1.0'
